function outVal = parseTreeHelper(tree)
% recursive function for reading the string generated by the tree
if isleaf(tree,1)
    %base case for recursion, returns end node value if leaf
    outVal = string(tree.Node(1));
    return
else
    %if an operator changes the &variable into a function name
    curVal = string(tree.Node(1));
    if curVal == "&+"
        curString = "plus(";
    elseif curVal == "&*"
        curString = "times(";
    else
        curString = "error(";
    end
    %finds the children of the current node
    children = getchildren(tree,1);
    %recursivly calls the function adding the &functions, children, and
    %syntax
    curVal = strcat(curString, parseTreeHelper(tree.subtree(children(1))), ",", parseTreeHelper(tree.subtree(children(2))),")");
    %return
    outVal = curVal;
end